### ISSUE TITLE
Version 0.71 crashes with error when scanning library.

### ISSUE THREAD

**Issue by henry-yopp** [CogentHub/HomeLoader#1]
Line 26864 (File "C:\Program Files )x86)\HomeLoader\System\HomeLoaderLibrar.exe"):

Error: Variable used without being declared.

**Comment by CogentHub** [comment]
Thanks for reporting. Saw it too late, my bad. A lot changed since 0.75, please try again. It should be fixed.

**Comment by CogentHub** [comment]
I have released a new version, HomeLoader 0.77. Please try the new version, the issue you mentioned should now be fixed.
